In [1]:
import pandas as pd

In [2]:
u202 = pd.read_csv("https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/u202.csv")
u203 = pd.read_csv("https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/u203.csv")
u302 = pd.read_csv("https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/u302.csv")

In [3]:
u202[u202['znamka'].isnull()]

   cisloStudenta  predmet  znamka den
0              1   Chemie     NaN  pá
9              9  Dějepis     NaN  pá

In [4]:
u202.dropna(inplace=True)
u203.dropna(inplace=True)
u302.dropna(inplace=True)

In [5]:
u202['mistnost'] = 'u202'
u203['mistnost'] = 'u203'
u302['mistnost'] = 'u302'

In [6]:
maturita = pd.concat([u202, u203, u302], ignore_index=True)
maturita

    cisloStudenta           predmet  znamka den mistnost
0               2           Dějepis     3.0  pá     u202
1               3        Matematika     2.0  út     u202
2               2  Společenské vědy     2.0  pá     u202
3               4          Biologie     1.0  pá     u202
4               5           Dějepis     1.0  po     u202
5               6            Fyzika     2.0  čt     u202
6               7           Dějepis     4.0  po     u202
7               8        Matematika     2.0  po     u202
8              10            Chemie     2.0  st     u202
9               3            Chemie     5.0  út     u202
10             11        Matematika     1.0  st     u202
11             12          Biologie     4.0  st     u202
12             10           Dějepis     5.0  st     u202
13              5  Společenské vědy     3.0  po     u203
14             13        Matematika     5.0  po     u203
15              7       Informatika     3.0  po     u203
16             12            Fyzika     3.0  st     u203
17             14            Fyzika     3.0  st     u203
18             15            Chemie     3.0  pá     u203
19             16       Informatika     2.0  út     u203
20              8           Zeměpis     1.0  po     u203
21             17            Fyzika     4.0  po     u203
22             15  Společenské vědy     3.0  pá     u203
23             20            Fyzika     2.0  čt     u203
24             21          Biologie     4.0  st     u203
25             22           Zeměpis     3.0  út     u203
26             23       Informatika     1.0  po     u302
27             23  Společenské vědy     1.0  po     u302
28              6        Matematika     5.0  čt     u302
29              4       Informatika     1.0  pá     u302
30             16          Biologie     2.0  út     u302
31             20        Matematika     1.0  čt     u302
32             21       Informatika     4.0  st     u302
33             11            Chemie     5.0  st     u302
34             14           Dějepis     3.0  st     u302
35             13            Chemie     4.0  po     u302
36             22       Informatika     3.0  út     u302
37             17        Matematika     3.0  po     u302

In [7]:
maturita.to_csv('maturita.csv', index=False)